- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Upgrading all packages (CentOS)
  yum:
    name: '*'
    state: latest 
  when: ansible_os_family == "RedHat"

- name: Install a few more packages
  package:
    name: "{{item}}"
    state: installed
  with_items:
   - curl
   
